site_name: Paladin
repo_name: LF-Decentralized-Trust-labs/paladin
repo_url: https://github.com/LF-Decentralized-Trust-labs/paladin
theme:
  name: material
  custom_dir: overrides
  logo: assets/paladin-logo-light.svg
  logo_dark: assets/paladin-logo-dark.svg
  favicon: assets/paladin-icon-light.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: paladin
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: paladin-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  primary: custom
  features:
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sidebar
    - navigation.tracking
    - navigation.path
    - navigation.indexes
extra_css:
  - stylesheets/paladin.css
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - include-markdown:
      rewrite_relative_urls: false
  - literate-nav
  - search
  - mike
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike
  generator: false
exclude_docs: |
  _includes/
nav:
  - Introduction:
    - Introduction: index.md
    - Privacy Preserving Tokens: concepts/tokens.md
    - Private EVM Smart Contracts: concepts/private_evm.md
    - Advanced Cryptography: concepts/advanced_crypto.md
    - Atomic EVM Programmability: concepts/atomic_programmability.md
    - Full Enterprise Privacy Stack: concepts/full_stack.md
    - Cloud Native Runtime: concepts/cloud_native.md
  - Architecture:
    - Overview: architecture/overview.md
    - Programming model: architecture/programming_model.md
    - Domains: architecture/domains.md
    - Zeto - ZKP Tokens: architecture/zeto.md
    - Noto - Notarized Tokens: architecture/noto.md
    - Pente - EVM Privacy Groups: architecture/pente.md
    - Key management: architecture/key_management.md
    - State store: architecture/state_store.md
    - Atomic interop: architecture/atomic_interop.md
    - Data Transports & Registry: architecture/data_and_registry.md
    - Ledger Layers: architecture/ledger_layers.md
  - Getting Started:
    - Installation: 
      - Default Installation: getting-started/installation.md
      - Advanced Installation: getting-started/installation-advanced.md
      - Manual Installation: getting-started/installation-manual.md
    - User Interface: getting-started/user-interface.md
    - Troubleshooting: getting-started/troubleshooting.md
  - Tutorials:
    - Introduction: tutorials/index.md
    - Hello World: tutorials/hello-world.md
    - Public Smart Contract: tutorials/public-storage.md
    - Private Smart Contract: tutorials/private-storage.md
    - Notarized Tokens: tutorials/notarized-tokens.md
    - Bond Issuance: tutorials/bond-issuance.md
    - Wholesale CBDC: tutorials/zkp-cbdc.md
  - Reference:
    - APIs: reference/apis/*.md
    - Types: reference/types/*.md
    - Kubernetes CRDs: reference/crds/*.md
    - Architecture: reference/architecture.md
    - Commands: reference/commands.md
    - Roadmap: reference/roadmap.md
  - Contributing:
    - How to Contribute: contributing/how-to-contribute.md
    - Reporting a Bug: contributing/reporting-a-bug.md
    - Requesting a Change: contributing/requesting-a-change.md
    - Asking a Question: contributing/asking-a-question.md
  - FAQs: faqs.md
  - Glossary: glossary.md
