# Installation mode. This setting determines which Custom Resources (CRs) will be installed by default when deploying this chart.
# Supported modes:
# - devnet: Installs a default Paladin network (3 nodes) along with the related Domains and Smart Contracts CRs.
# - basenet: Deploys the Domains and Smart Contracts CRs without installing the Paladin network.
# - none (or left empty): Only the operator will be installed.
mode: devnet

# Number of Paladin and besu nodes to deploy. This setting is only relevant when mode is set to "devnet".
nodeCount: 3

# Default values for paladin-operator
operator:
  name: paladin-operator
  namespace: paladin
  image:
    repository: ghcr.io/lf-decentralized-trust-labs/paladin-operator
    tag: main
    pullPolicy: Always

  serviceAccount:
    create: true
    automount: true
    annotations: {}

  podSecurityContext:
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
      scheme: HTTP
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
      scheme: HTTP

  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

  env:
    - name: CONFIG_PATH
      value: /etc/config

  # Volumes configuration
  volumes:
  - name: config
    configMap:
      name: paladin-operator     

  volumeMounts:
  - name: config
    mountPath: /etc/config/config.json    # Where the file will be mounted in the container
    subPath: config.json                  # The key (file) from the ConfigMap to mount
                     
  labels:
    control-plane: controller-manager

  annotations: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}

  service:
    type: ClusterIP
    port: 80

  configMap:
    # Referring to the external config.yaml file
    dataFile: assets/config.json
# Prometheus dependencies
prometheus:
  enabled: false
  prometheus:
    namespace: prometheus 
  alertmanager:
    enabled: false 
  server:
    enabled: false
  pushgateway:
    enabled: false  # Enable if you need the push gateway

paladin:
  nodeNamePrefix: node
  image:
    repository: ghcr.io/lf-decentralized-trust-labs/paladin
    tag: main
    pullPolicy: Always
  labels:
    app: paladin
  baseNodePort: 31548
  
besu:
  nodeNamePrefix: node
  image:
    repository: hyperledger/besu
    tag: latest
    pullPolicy: Always
  labels:
    app: besu
  baseNodePort: 31545
  
postgres: # the postgres container runs as a sidecar to the paladin container
  image:
    repository: postgres
    tag: latest
    pullPolicy: Always

# Install CRDs as part of the chart installation
# When this is set to false, the CRDs are expected to be installed separately
installCRDs: false
