apiVersion: core.paladin.io/v1alpha1
kind: TransactionInvoke
metadata:
  labels:
    app.kubernetes.io/name: operator-go
    app.kubernetes.io/managed-by: kustomize
  name: zeto-anon-enc
spec:
  node: node1
  from: zeto.operator
  txType: public
  toTemplate: '{{ index .status.resolvedContractAddresses "zeto-factory" }}'
  requiredContractDeployments:
  - "zeto-factory"
  - "zeto-impl-anon-enc"
  - "zeto-g16-check-hashes-value"
  - "zeto-g16-check-inputs-outputs"
  - "zeto-g16-check-inputs-outputs-batch"
  - "zeto-g16-verifier-anon-enc"
  - "zeto-g16-verifier-anon-enc-batch"
  function: registerImplementation
  paramsJSONTemplate: |
    {
      "name": "Zeto_AnonEnc",
      "implementation": {
        "implementation":        "{{ index .status.resolvedContractAddresses "zeto-impl-anon-enc" }}",
        "depositVerifier":       "{{ index .status.resolvedContractAddresses "zeto-g16-check-hashes-value" }}",
        "withdrawVerifier":      "{{ index .status.resolvedContractAddresses "zeto-g16-check-inputs-outputs" }}",
        "batchWithdrawVerifier": "{{ index .status.resolvedContractAddresses "zeto-g16-check-inputs-outputs-batch" }}",
        "verifier":              "{{ index .status.resolvedContractAddresses "zeto-g16-verifier-anon-enc" }}",
        "batchVerifier":         "{{ index .status.resolvedContractAddresses "zeto-g16-verifier-anon-enc-batch" }}"
      }
    }
  abiJSON: |
    [
      {
        "inputs": [
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "components": [
              {
                "internalType": "address",
                "name": "implementation",
                "type": "address"
              },
              {
                "internalType": "address",
                "name": "depositVerifier",
                "type": "address"
              },
              {
                "internalType": "address",
                "name": "withdrawVerifier",
                "type": "address"
              },
              {
                "internalType": "address",
                "name": "verifier",
                "type": "address"
              },
              {
                "internalType": "address",
                "name": "batchVerifier",
                "type": "address"
              },
              {
                "internalType": "address",
                "name": "batchWithdrawVerifier",
                "type": "address"
              }
            ],
            "internalType": "struct ZetoTokenFactory.ImplementationInfo",
            "name": "implementation",
            "type": "tuple"
          }
        ],
        "name": "registerImplementation",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
      }
    ]
