apiVersion: core.paladin.io/v1alpha1
kind: TransactionInvoke
metadata:
  labels:
    app.kubernetes.io/name: operator-go
    app.kubernetes.io/managed-by: kustomize
  name: zeto-anon
spec:
  from: zeto.operator
  txType: public
  toTemplate: '{{ index .status.resolvedContractAddresses "zeto-factory" }}'
  requiredContractDeployments:
    - 'zeto-factory'
    - 'zeto-impl-anon'
    - 'zeto-g16-deposit'
    - 'zeto-g16-withdraw'
    - 'zeto-g16-withdraw-batch'
    - 'zeto-g16-anon'
    - 'zeto-g16-anon-batch'
  function: registerImplementation
  paramsJSONTemplate: |
    {
      "name": "Zeto_Anon",
      "implementation": {
        "implementation":        "{{ index .status.resolvedContractAddresses "zeto-impl-anon" }}",
        "verifiers": {
          "verifier":              "{{ index .status.resolvedContractAddresses "zeto-g16-anon" }}",
          "depositVerifier":       "{{ index .status.resolvedContractAddresses "zeto-g16-deposit" }}",
          "withdrawVerifier":      "{{ index .status.resolvedContractAddresses "zeto-g16-withdraw" }}",
          "batchVerifier":         "{{ index .status.resolvedContractAddresses "zeto-g16-anon-batch" }}",
          "batchWithdrawVerifier": "{{ index .status.resolvedContractAddresses "zeto-g16-withdraw-batch" }}",
          "lockVerifier":          "0x0000000000000000000000000000000000000000",
          "batchLockVerifier":     "0x0000000000000000000000000000000000000000"
        }
      }
    }
  abiJSON: |
    [
      {
        "inputs": [
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "components": [
              {
                "internalType": "address",
                "name": "implementation",
                "type": "address"
              },
              {
                "name": "verifiers",
                "type": "tuple",
                "components": [
                  {
                    "internalType": "address",
                    "name": "verifier",
                    "type": "address"
                  },
                  {
                    "internalType": "address",
                    "name": "depositVerifier",
                    "type": "address"
                  },
                  {
                    "internalType": "address",
                    "name": "withdrawVerifier",
                    "type": "address"
                  },
                  {
                    "internalType": "address",
                    "name": "batchVerifier",
                    "type": "address"
                  },
                  {
                    "internalType": "address",
                    "name": "batchWithdrawVerifier",
                    "type": "address"
                  },
                  {
                    "internalType": "address",
                    "name": "lockVerifier",
                    "type": "address"
                  },
                  {
                    "internalType": "address",
                    "name": "batchLockVerifier",
                    "type": "address"
                  }
                ]
              }
            ],
            "internalType": "struct ZetoTokenFactory.ImplementationInfo",
            "name": "implementation",
            "type": "tuple"
          }
        ],
        "name": "registerImplementation",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
      }
    ]
