## Append samples of your project ##
resources:
- cert_issuer_selfsigned.yaml
- core_v1alpha1_paladin_node1.yaml
- core_v1alpha1_paladin_node2.yaml
- core_v1alpha1_paladin_node3.yaml
- core_v1alpha1_besu_node1.yaml
- core_v1alpha1_besu_node2.yaml
- core_v1alpha1_besu_node3.yaml
- core_v1alpha1_besugenesis.yaml
- core_v1alpha1_paladinregistry.yaml
- core_v1alpha1_paladindomain_noto.yaml
- core_v1alpha1_paladindomain_pente.yaml
- core_v1alpha1_paladindomain_zeto.yaml
- core_v1alpha1_paladinregistration_node1_admin.yaml
- core_v1alpha1_paladinregistration_node2.yaml
- core_v1alpha1_paladinregistration_node3.yaml
- core_v1alpha1_transactioninvoke_zeto_register_anon.yaml
- core_v1alpha1_transactioninvoke_zeto_register_anon_enc.yaml
- core_v1alpha1_transactioninvoke_zeto_register_anon_nullifier.yaml
# Smart contracts - note these CRs are generate dynamically by the build
- core_v1alpha1_smartcontractdeployment_registry.yaml
- core_v1alpha1_smartcontractdeployment_noto_factory.yaml
- core_v1alpha1_smartcontractdeployment_pente_factory.yaml
- core_v1alpha1_smartcontractdeployment_zeto_factory.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_check_inputs_outputs.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_check_inputs_outputs_batch.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_check_nullifier.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_check_nullifier_batch.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_check_hashes_value.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_verifier_anon.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_verifier_anon_batch.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_verifier_anon_enc.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_verifier_anon_enc_batch.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_verifier_anon_nullifier.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_verifier_anon_nullifier_batch.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_check_nullifiers_owner.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_check_nullifiers_owner_batch.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_check_utxos_owner.yaml
- core_v1alpha1_smartcontractdeployment_zeto_g16_check_utxos_owner_batch.yaml
- core_v1alpha1_smartcontractdeployment_zeto_impl_anon.yaml
- core_v1alpha1_smartcontractdeployment_zeto_impl_anon_enc.yaml
- core_v1alpha1_smartcontractdeployment_zeto_impl_anon_nullifier.yaml
- core_v1alpha1_smartcontractdeployment_zeto_poseidon_unit2l.yaml
- core_v1alpha1_smartcontractdeployment_zeto_poseidon_unit3l.yaml
- core_v1alpha1_smartcontractdeployment_zeto_smt_lib.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
