contracts:
  factory:
    abiAndBytecode:
      path: ./abis/ZetoFactory.json
  # the Zeto factory is a CloneFactory, which needs implementation
  # contracts to be set
  implementations:
    # for the deposit transaction
    - name: Groth16Verifier_CheckHashesValue
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckHashesValue.json
    # for the withdraw transaction
    - name: Groth16Verifier_CheckInputsOutputsValue
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckInputsOutputsValue.json
    # for the withdraw transaction with batch inputs
    - name: Groth16Verifier_CheckInputsOutputsValueBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckInputsOutputsValueBatch.json
    # for the withdraw transaction with nullifiers
    - name: Groth16Verifier_CheckNullifierValue
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckNullifierValue.json
    # for the withdraw transaction with batch inputs and nullifiers
    - name: Groth16Verifier_CheckNullifierValueBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckNullifierValueBatch.json
    # for lock (without nullifiers)
    - name: Groth16Verifier_CheckUtxosOwner
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckUtxosOwner.json
    # for batch lock (without nullifiers)
    - name: Groth16Verifier_CheckUtxosOwnerBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckUtxosOwnerBatch.json
    # for lock (with nullifiers)
    - name: Groth16Verifier_CheckNullifiersOwner
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckNullifiersOwner.json
    # for batch lock (with nullifiers)
    - name: Groth16Verifier_CheckNullifiersOwnerBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckNullifiersOwnerBatch.json
    # for the Zeto_Anon token
    - name: Groth16Verifier_Anon
      abiAndBytecode:
        path: ./abis/Groth16Verifier_Anon.json
    - name: Groth16Verifier_AnonBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonBatch.json
    - name: Zeto_Anon
      verifier: Groth16Verifier_Anon
      batchVerifier: Groth16Verifier_AnonBatch
      depositVerifier: Groth16Verifier_CheckHashesValue
      withdrawVerifier: Groth16Verifier_CheckInputsOutputsValue
      batchWithdrawVerifier: Groth16Verifier_CheckInputsOutputsValueBatch
      lockVerifier: Groth16Verifier_CheckUtxosOwner
      batchLockVerifier: Groth16Verifier_CheckUtxosOwnerBatch
      circuitId: anon
      cloneable: true
      abiAndBytecode:
        path: ./abis/Zeto_Anon.json
    # for the Zeto_AnonEnc token
    - name: Groth16Verifier_AnonEnc
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonEnc.json
    - name: Groth16Verifier_AnonEncBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonEncBatch.json
    - name: Zeto_AnonEnc
      verifier: Groth16Verifier_AnonEnc
      batchVerifier: Groth16Verifier_AnonEncBatch
      depositVerifier: Groth16Verifier_CheckHashesValue
      withdrawVerifier: Groth16Verifier_CheckInputsOutputsValue
      batchWithdrawVerifier: Groth16Verifier_CheckInputsOutputsValueBatch
      lockVerifier: Groth16Verifier_CheckUtxosOwner
      batchLockVerifier: Groth16Verifier_CheckUtxosOwnerBatch
      circuitId: anon_enc
      cloneable: true
      abiAndBytecode:
        path: ./abis/Zeto_AnonEnc.json
    # for the Zeto_AnonNullifier token
    - name: PoseidonUnit2L
      abiAndBytecode:
        path: ./abis/Poseidon2.json
    - name: PoseidonUnit3L
      abiAndBytecode:
        path: ./abis/Poseidon3.json
    - name: SmtLib
      abiAndBytecode:
        path: ./abis/SmtLib.json
    - name: Groth16Verifier_AnonNullifier
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonNullifier.json
    - name: Groth16Verifier_AnonNullifierBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonNullifierBatch.json
    - name: Zeto_AnonNullifier
      verifier: Groth16Verifier_AnonNullifier
      batchVerifier: Groth16Verifier_AnonNullifierBatch
      depositVerifier: Groth16Verifier_CheckHashesValue
      withdrawVerifier: Groth16Verifier_CheckNullifierValue
      batchWithdrawVerifier: Groth16Verifier_CheckNullifierValueBatch
      lockVerifier: Groth16Verifier_CheckNullifiersOwner
      batchLockVerifier: Groth16Verifier_CheckNullifiersOwnerBatch
      circuitId: anon_nullifier
      cloneable: true
      abiAndBytecode:
        path: ./abis/Zeto_AnonNullifier.json
