name: Paladin Buildx
permissions:
  contents: write
  packages: write
  id-token: write
  
on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
      image_tags:
        required: true
        type: string
        description: 'List of image tags separated by comma'
      push:
        required: false
        type: boolean
        default: true
    secrets:
      username:
        required: false
      password:
        required: false

jobs:
  set-repository:
    runs-on: ubuntu-latest
    outputs:
      repository: ${{ steps.modify_repo.outputs.repository }}
    steps:
      - uses: actions/checkout@v4
      - name: Set Repository Name
        id: modify_repo
        uses: ./.github/actions/repository
        with:
          repository: ${{ inputs.repository }}
          registry: ${{ inputs.registry }}

  core-macos:
    needs: set-repository
    uses: ./.github/workflows/build-image.yaml
    with:
      dockerfile: ./Dockerfile
      registry: ${{ inputs.registry }}
      image: ${{ needs.set-repository.outputs.repository }}/paladin
      image_tag: "${{ github.sha }}-arm64"
      push: ${{ inputs.push }}
      platforms: linux/arm64
      runs-on: ubuntu-latest
    secrets:
      username: ${{ secrets.username }}
      password: ${{ secrets.password }}

  core-ubuntu:
    needs: set-repository
    uses: ./.github/workflows/build-image.yaml
    with:
      dockerfile: ./Dockerfile
      registry: ${{ inputs.registry }}
      image: ${{ needs.set-repository.outputs.repository }}/paladin
      image_tag: "${{ github.sha }}-amd64"
      push: ${{ inputs.push }}
      platforms: linux/amd64
      runs-on: ubuntu-latest
    secrets:
      username: ${{ secrets.username }}
      password: ${{ secrets.password }}

  operator-ubuntu:
    needs: set-repository
    uses: ./.github/workflows/build-image.yaml
    with:
      dockerfile: ./operator/Dockerfile
      registry: ${{ inputs.registry }}
      image: ${{ needs.set-repository.outputs.repository }}/paladin-operator
      image_tag: ${{ github.sha }}-amd64
      push: ${{ inputs.push }}
      platforms: linux/amd64
      runs-on: ubuntu-latest
    secrets:
      username: ${{ secrets.username }}
      password: ${{ secrets.password }}

  operator-macos:
    needs: set-repository
    uses: ./.github/workflows/build-image.yaml
    with:
      dockerfile: ./operator/Dockerfile
      registry: ${{ inputs.registry }}
      image: ${{ needs.set-repository.outputs.repository }}/paladin-operator
      image_tag: ${{ github.sha }}-arm64
      push: ${{ inputs.push }}
      platforms: linux/arm64
      runs-on: ubuntu-latest
    secrets:
      username: ${{ secrets.username }}
      password: ${{ secrets.password }}

  core-docker-manifest:
    if: ${{ inputs.push }}
    needs: [set-repository, core-macos, core-ubuntu]
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ inputs.registry }}/${{ needs.set-repository.outputs.repository }}/paladin
    steps:
      - uses: actions/checkout@v4

      - name: Set lower case image name
        run: |
          echo "TEMP_IMAGE=$IMAGE:$GITHUB_SHA" >> $GITHUB_ENV
          echo "Temp image: $IMAGE:$GITHUB_SHA"

      - name: Docker registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Create and push core manifest
        env:
          IMAGE_TAGS: ${{ inputs.image_tags }}
        run: |
          echo "## Core images built" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY

          IFS=',' read -ra TAG_ARRAY <<< "$IMAGE_TAGS"
          for tag in "${TAG_ARRAY[@]}"; do
            docker manifest create $IMAGE:$tag \
            --amend $TEMP_IMAGE-arm64 \
            --amend $TEMP_IMAGE-amd64
            docker manifest push $IMAGE:$tag
            echo "- $IMAGE:$tag" >> $GITHUB_STEP_SUMMARY
          done

  operator-docker-manifest:
    if: ${{ inputs.push }}
    needs: [set-repository, operator-macos, operator-ubuntu]
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ inputs.registry }}/${{ needs.set-repository.outputs.repository }}/paladin-operator
    steps:
      - uses: actions/checkout@v4

      - name: Set lower case image name
        run: |
          echo "TEMP_IMAGE=$IMAGE:$GITHUB_SHA" >> $GITHUB_ENV
          echo "Temp image: $IMAGE:$GITHUB_SHA"

      - name: Docker registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Create and push operator manifest
        env:
          IMAGE_TAGS: ${{ inputs.image_tags }}
        run: |
          echo "## Operator images built" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          
          IFS=',' read -ra TAG_ARRAY <<< "$IMAGE_TAGS"
          for tag in "${TAG_ARRAY[@]}"; do
            docker manifest create $IMAGE:$tag \
            --amend $TEMP_IMAGE-arm64 \
            --amend $TEMP_IMAGE-amd64
            docker manifest push $IMAGE:$tag
            echo "- $IMAGE:$tag" >> $GITHUB_STEP_SUMMARY
          done
