name: Paladin Operator Build

on:
  push:
    branches:
      - main
    paths:
      - 'operator/**'
  pull_request:
    paths:
      - 'operator/**'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: paladin
      NAMESPACE: paladin

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      # - name: Go Lint
      #   working-directory: operator
      #   run: make lint

      # - name: Unit Tests
      #   working-directory: operator
      #   run: make test

      # - name: End-to-End Tests
      #   working-directory: operator
      #   run: make test-e2e

      - name: Create Kubernetes Kind Cluster
        uses: helm/kind-action@v1
        with:
          install_only: true # only install kind, the cluster creation is managed by the deploy step
          ignore_failed_clean: true

      - name: Deploy Operator
        working-directory: operator
        run: gradle deploy -PclusterName=${{ env.CLUSTER_NAME }} -Pnamespace=${{ env.NAMESPACE }} 

      - name: Uninstall Operator
        working-directory: operator
        run: gradle clean -PclusterName=${{ env.CLUSTER_NAME }} -Pnamespace=${{ env.NAMESPACE }} -PdeleteCluster=true