name: Paladin CI build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # uncomment database setup as needed
    # services:
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_PASSWORD: my-secret
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v25.1/protoc-25.1-linux-x86_64.zip
          unzip protoc-25.1-linux-x86_64.zip -d protoc
          echo "${PWD}/protoc/bin" >> $GITHUB_PATH

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true
          
      # Set up AWS credentials from GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 604386504253.dkr.ecr.us-east-2.amazonaws.com
    
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew -PcomposeLogs=true --parallel build

        # env:
        #   CREATE_TEST_DB: 0 # github action setup a PSQL db service, so no need to create a test db again
        #   POSTGRES_HOSTNAME: postgres
        #   POSTGRES_PASSWORD: my-secret
        #   POSTGRES_PORT: 5432
#  docker-build:
#    runs-on: ubuntu-latest
#    # uncomment database setup as needed
#    # services:
#    #   postgres:
#    #     image: postgres
#    #     env:
#    #       POSTGRES_PASSWORD: my-secret
#    #     options: >-
#    #       --health-cmd pg_isready
#    #       --health-interval 10s
#    #       --health-timeout 5s
#    #       --health-retries 5
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Build Docker image
#        working-directory: .
#        run: make docker
#        # env:
#        #   CREATE_TEST_DB: 0 # github action setup a PSQL db service, so no need to create a test db again
#        #   POSTGRES_HOSTNAME: postgres
#        #   POSTGRES_PASSWORD: my-secret
#        #   POSTGRES_PORT: 5432
